### ISSUE TITLE
Error 503

### ISSUE THREAD

**Issue by nyetke** [movestore/animation-moveVis#1]
I keep getting the error which reads "Error in curl_download(url = url, destfile = file): HTTP error 503" when trying to use this app with MoveApps. Can someone please explain to me what this means and how to resolve the issue?

**Comment by andreakoelzsch** [comment]
Dear nyetke, thanks for the issue. I have just tested to App and could not reproduce the error. From the error, I do suspect there are problems with downloading some maps from OSM, which we have experienced recently in some other App. Which background map option did you use?

**Comment by nyetke** [comment]
Thanks for getting back to me! I've tried both the watercolor map and the topo map. Both selections have produced errors.

**Comment by andreakoelzsch** [comment]
Thanks for the details. We are presently updating the App to use stamen in stead of osm, but as the App is working ok for my data, I would like to ask you: Please would you share your workflow with me (andreakoelzsch) on MoveApps, so that I can reproduce it? If the data for the workflow are not public, could you send me (akoelzsch@ab.mpg.de) the rds that comes out of your Movebank App? Of course, this can also be just 2-3 locations, if they give the error.

**Comment by nyetke** [comment]
Hi Andrea,

Sorry I'm just getting back to you about this. I shared my workflow with you on MoveApps and attached is the rds with my data that you requested. Please let me know if you need anything else and thank you so much for your help!

Best,
Nikki Yetke
________________________________

**Comment by andreakoelzsch** [comment]
Dear NIkki,
Thanks a lot for sending the file and all your details to find the error. In the end it was something that we experience with several Apps lately, namely that Open Street Map does not work for downloading background maps. I am not sure what is going on there, but will contact the R package developer. I have now changed to possible map backgrounds to 3 different types of "carto", and it works. I have shared a workflow with you, see also the settings in the Animation App. All the best, Andrea
