### ISSUE TITLE
ERROR: ./start-process.sh: line 9:    39 Killed

### ISSUE THREAD

**Issue by sarahcd** [movestore/animation-moveVis#11]
Hi @andreakoelzsch , following up on my comment in [issue9](https://github.com/movestore/animation-moveVis/issues/9).

Taking the workflow you shared yesterday (or Wed?), if I keep everything the same but increase the resolution setting from 0.2 to 0.3, I get an error. I get the same error in other workflows.

![image](https://github.com/movestore/animation-moveVis/assets/15783614/de97243d-e204-49f6-992d-7e13b536fba2)

`
Hi @andreakoelzsch , I think it's worth investigating the resolution setting. I played around with the workflow you shared. I can't return to the original to be absolutely sure, but from my notes of what I did, simply updating the resolution setting from 0.2 to 0.8 leads to an error. Likewise, if I change the resolution setting from 0.8 to 0.2 in the other workflow I'm preparing, it runs. The outputs are very blurry so I'd like to increase it.
`

**Comment by andreakoelzsch** [comment]
@sarahcd Hi Sarah, I dont believe that this is the same error as in issue #9, the one you report here is definitely to do with memory limit kicking in. That means, you are requesting a background map that is of too high resolution for the spatial extent that your data have. So, if you go down in resolution (0.2) it works. You can confirm this by using a smaller spatial scale data set... does this make sense?
for the future: "XX killed" always means that MoveApps crashes due to memory limits. As said, we will move the system to double the memory hardware in the coming 2 weeks, hopefully that will improve things

**Comment by sarahcd** [comment]
Ok, thanks. To troubleshoot this further: I am increasing the resolution because I am trying to get an animation with a clear background map. They seem to always be super blurry. 

It seems there might be a different problem that animation is somehow not responding to the resolution setting. Clearly the code is considering it, because the memory limit occurs when the resolution setting gets large enough. But for the resolution settings that do work, I see no difference in the output.

Here are the same input settings but with resolution 0.3 on the left, 0.5 on the right. The background looks exactly the same to me.
<img width="856" alt="image" src="https://github.com/movestore/animation-moveVis/assets/15783614/4a3b49a4-fc99-4bcd-86ad-67ab5338e084">

Is this something I should make a separate ticket for?

**Comment by andreakoelzsch** [comment]
@sarahcd indeed, this is very strange, but really something that the moveVis pacakge would have to solve. Let me include it in working towards usage of our internal OSM mirror..
